server {
    listen 80;
    server_name purekit.cn;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name purekit.cn;

    ssl_certificate /etc/nginx/certs/purekit.cn_bundle.crt;
    ssl_certificate_key /etc/nginx/certs/purekit.cn.key;
    
    ssl_session_timeout 5m;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
    ssl_prefer_server_ciphers on;

    # 调大允许上传的文件大小
    client_max_body_size 50m;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location /api {
        proxy_pass http://purekit-backend:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
